#: import menu menu

MainWidget:


<MainWidget>:

    canvas.before:
        Rectangle:
            source : 'images/multiverse.jpg'
            size : self.size
    menu_widget : menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height*0.75

    MenuWidget:
        id : menu_widget

    Label :
        text : root.score_txt
        font_size: dp(20)
        font_name : 'fonts/Eurostile.ttf'
        size_hint : 0.2, 0.2
        pos_hint : {"x" : 0, "top" : 1}
